@baseUrl = http://localhost:8080/api
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmaW50cmFjayIsImlhdCI6MTc3NTI5NTQ2MywiZXhwIjoxNzc1Mjk2MzYzLCJzdWIiOiIwMUtOQlhOUkQxRTg4U0VWRldOWlFYRDBBUSJ9.vRrxuh-kRHuTzPQiP00j0wgL5_9s9Vck98ROqbxGLrI
@refreshToken = RT-01KNBXNZV8B4NES4XP81SYXRRN

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "username": "johndoe",
    "email": "john@example.com",
    "password": "password123"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json
# Authorization: Bearer {{accessToken}}
# x-secret-api: abcsecret

{
    "username": "johndoe",
    "password": "password123"
}

# ### Refresh Token
# POST {{baseUrl}}/auth/refresh
# Content-Type: application/json

# {{refreshToken}}

# ### Logout
# POST {{baseUrl}}/auth/logout
# Content-Type: application/json

# {{refreshToken}}

### Test Dummy
GET {{baseUrl}}/test
Content-Type: application/json
Authorization: Bearer {{accessToken}}
