spring.application.name=fintrack

app.APP_NAME=fintrack
app.JWT_SECRET_KEY=aVG6sHEdToZ+3xau2ocOXKXfDVhxpU5EWxw/NG7/AcM=
# app.JWT_INIT_VECTOR=XyeIIIMKFPW+ztFWw2Jofw==
app.JWT_EXPIRATION=900000

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true