spring.application.name=fintrack

app.APP_NAME=fintrack
app.JWT_SECRET_KEY=4ff9d1d1f0f0a4382fce448c055854bf9e0138440d3cf246e9d5ebd0ad331565
app.JWT_EXPIRATION=900000

spring.datasource.url=jdbc:postgresql://ep-withered-shadow-a1hd3uth-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_veTS4XLMbj6W
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true