spring.application.name=fintrack

app.APP_NAME=fintrack
app.JWT_SECRET_KEY=aVG6sHEdToZ+3xau2ocOXKXfDVhxpU5EWxw/NG7/AcM=
# app.JWT_INIT_VECTOR=XyeIIIMKFPW+ztFWw2Jofw==
app.JWT_EXPIRATION=900000

spring.datasource.url=jdbc:postgresql://ep-withered-shadow-a1hd3uth-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TqDrR0WlA1se
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true